# Generated by Django 5.2.6 on 2025-09-08 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_emailconfirmation"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="customuser",
            managers=[],
        ),
    ]
