# Generated by Django 5.2.6 on 2025-09-10 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_customuser_managers"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="emailconfirmation",
            options={
                "verbose_name": "Подтверждение email",
                "verbose_name_plural": "Подтверждения email",
            },
        ),
    ]
