# Generated by Django 5.2.6 on 2025-09-08 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("diary", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="entry",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Запись",
                "verbose_name_plural": "Записи",
            },
        ),
    ]
