# Generated by Django 5.2.6 on 2025-09-10 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diary", "0003_alter_entry_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name="entry",
            old_name="user",
            new_name="author",
        ),
        migrations.AddField(
            model_name="entry",
            name="tags",
            field=models.ManyToManyField(blank=True, to="diary.tag"),
        ),
    ]
